# docker-compose up -d

version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [npm, run, dev]
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - .:/app
