swagger: "2.0"
info:
  title: Archives API Specification
  version: "1.0"
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Health check route for server
      operationId: "getHealth"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Success message
